

# build stage go
FROM golang:alpine AS go-build-env
RUN apk --no-cache add build-base git bzr mercurial gcc
ADD ./src /go
RUN cd /go/github.com/lss/webapp && go build -o plural-web



# final stage
FROM alpine
WORKDIR /app
COPY --from=go-build-env /go/github.com/lss/webapp /app/
RUN chmod +x plural-web
ADD ./public /app/public
ADD ./templates /app/templates
ENTRYPOINT ./plural-web
EXPOSE 8000
