kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api-pod
        image: woodregistry.azurecr.io/woodgo/goscaleweb
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-auth
