

# build stage go
FROM golang:alpine AS go-build-env
RUN apk --no-cache add build-base git bzr mercurial gcc
ADD ./src /go
RUN cd /go && go build -o plural-web
#RUN cd /go/src/github.com/lss/webapp && go build -o plural-web


# build stage node
FROM node:alpine AS node-build-env
RUN apk --no-cache --update add openssh-client git nodejs && npm install -g grunt-cli
ADD ./src /src
RUN cd /src && npm install && grunt


# final stage
FROM alpine
WORKDIR /app
COPY --from=node-build-env /src /app/
COPY --from=go-build-env /go /app/
RUN chmod +x plural-web
ENTRYPOINT ./plural-web
